---
- name: add mariadb repository
  template:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo
- name: install mariadb
  yum:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python
    - mariadb-devel
- name: start mariadb
  service: name=mysql enabled=yes state=started

- name: create project_name database
  mysql_db:
    name: "{{item}}"
    state: present
  with_items: "{{databases}}"

- name: add maria database users
  mysql_user:
    name: "{{item.user}}"
    password: "{{item.user}}"
    host: "{{ item.host | default('localhost') }}"
    priv: "*.*:ALL"
    state: present
  with_items: "{{users}}"

- name: my.cnf changes for allowing access from outside
  blockinfile:
    path: /etc/my.cnf
    block: |
      [mysqld]
      wait_timeout = 86400
      max_allowed_packet = 500M
      bind-address = 0.0.0.0

- name: restarting mysql service
  become: yes
  service:
    name: mysql
    state: restarted
